assign/urls.py
from django.urls import path, include
from .views import signupfunc, loginfunc, logoutfunc, menufunc, notificationfunc, projectfunc, project_detailfunc, project_addfunc, project_resourcefunc, memberfunc, member_resourcefunc, working_timefunc


urlpatterns = [
    path('signup/', signupfunc, name='signup'),
    path('login/', loginfunc, name='login'),
    path('logout/', logoutfunc, name='logout'),
    path('menu/', menufunc, name='menu'),
    path('notification/', notificationfunc, name='notification'),
    path('project/', projectfunc, name='project'),
    path('project/<int:pk>', project_detailfunc, name='project_detail'),
    path('project/add', project_addfunc, name='project_add'),
    path('project_resource/<int:pk>', project_resourcefunc, name='project_resource'),
    path('member/', memberfunc, name='member'),
    path('member_resource/<int:pk>', member_resourcefunc, name='member_resource'),
    path('working_time/', working_timefunc, name='working_time'),
]

vassign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assign.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

assign/models.py
from django.db import models
from users.models import User

# Create your models here.

class Notification(models.Model):
    """通知"""
    content = models.CharField(max_length=200)
    is_checked = models.BooleanField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '[Alert] ' + self.content



class ProjectPhase(models.Model):
    """案件のフェーズ"""
    phase = models.CharField(max_length=20)

    def __str__(self):
        return self.phase


class Project(models.Model):
    """案件"""
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    # start_date = models.CharField(max_length=10)
    # end_date = models.CharField(max_length=10)
    phase = models.ForeignKey(ProjectPhase, on_delete=models.PROTECT)
    user = models.ManyToManyField(
        User,
        through="ProjectMember",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + ' [' + self.start_date.strftime('%Y-%m-%d')[:-3] + '-' + self.end_date.strftime('%Y-%m-%d')[:-3] + '] '


class ProjectMember(models.Model):
    """案件×メンバー"""
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["project", "user"],
                name="project_member_unique"
            ),
        ]


    def __str__(self):
        return self.project.name + ' | ' + self.user.username


class MonthlyWorkingTime(models.Model):
    """月次の稼働時間の予定と実績"""
    project_member = models.ForeignKey(ProjectMember, default=0, on_delete=models.CASCADE)
    target_month = models.DateField()
    planed_working_time = models.IntegerField()
    actual_working_time = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_member.project.name + ' | ' + self.project_member.user.username + ' | ' + self.target_month.strftime('%Y-%m-%d')[:-3]


class DailyWorkingTime(models.Model):
    """日次の稼働時間の実績"""
    project_member = models.ForeignKey(ProjectMember, default=0, on_delete=models.CASCADE)
    target_day = models.DateField()
    target_month = models.DateField()
    working_time = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_member + self.target_month.strftime('%Y-%m-%d')[:-3] + self.target_day.strftime('%Y-%m-%d')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
import uuid as uuid_lib

# Create your models here.

class Role(models.Model):

    name = models.CharField(_('Role'), max_length=150, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Role')
        verbose_name_plural = _('Roles')

class User(AbstractBaseUser, PermissionsMixin):
    """ユーザー AbstractUserをコピペし編集"""

    # uuid = models.UUIDField(default=uuid_lib.uuid4,
    #                         primary_key=True, editable=False)
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    full_name = models.CharField(_('full name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_management = models.BooleanField(default=False)
    role = models.ForeignKey(
        Role,
        verbose_name=_('role'),
        null=True,
        help_text=_('Specific Roles for this user.'),
        related_name="user_set",
        related_query_name="user",
        on_delete=models.PROTECT,
    )
    # role_id = models.IntegerField(_('role id'), null=True)
    unit_price = models.IntegerField(_('unit price(万円/月)'), null=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', ]

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # 既存メソッドの変更
    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name

templates/base.html
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  {% block customcss %}
  {% endblock customcss %}

  <title>V-assing</title>
</head>

<body>
  <div class="alert alert-primary d-flex justify-content-between" role="alert">
    <a href="{% url 'menu' %}"><div>V-assign</div></a>
    {% block header %}
    {% endblock header %}
    <a href="{% url 'logout' %}">ログアウト</a>
  </div>

  {% block content %}
  {% endblock content %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock script %}
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<form class="form-signin" method="POST" action=''>{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">ログインする</h1>
  <!-- {% if error %}
  {{ error }}
  {% endif %} -->
  <label for="inputEmail" class="sr-only">メールアドレス</label>
  <input type="text" id="inputEmail" class="form-control" name="username" placeholder="ユーザーネーム" required autofocus>
  <label for="inputPassword" class="sr-only">パスワード</label>
  <input type="password" id="inputPassword" class="form-control" name="password" placeholder="パスワード" required>
  <button class="btn btn-lg btn-primary btn-block" type="submit">ログイン</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
</form>
{% endblock content %}

templates/member.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
  <h1>メンバーリスト</h1>
{% endblock header %}

{% block content %}
<div class="container">
  {% for member in member_list %}
  <div class="alert alert-success" role="alert">
    <p>{{ member.username }}</p>
    <a href="{% url 'member_resource' member.pk %}" class="btn btn-primary btn active" role="button" aria-pressed="true">稼働状況</a>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/member_resource.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>稼働状況</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <div class="alert alert-success" role="alert">
    <p>{{ member.username }}</p>
  </div>
</div>
{% endblock content %}

templates/menu.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
  <h1>メニュー</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <a href="{% url 'notification' %}">
    <div class="alert alert-success" role="alert">通知</div>
  </a>
  <a href="{% url 'project' %}">
    <div class="alert alert-success" role="alert">案件管理</div>
  </a>
  <a href="{% url 'member' %}">
    <div class="alert alert-success" role="alert">メンバー管理</div>
  </a>
  <a href="{% url 'working_time' %}">
    <div class="alert alert-success" role="alert">稼働実績</div>
  </a>
</div>
{% endblock content %}

templates/notification.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>通知リスト</h1>
{% endblock header %}

{% block content %}
<div class="container">
  {% for notification in notification_list %}
  <div class="alert alert-success" role="alert">
    <p>[Alert] {{ notification.content }}</p>
    <a href="#" class="btn btn-primary btn active" role="button" aria-pressed="true">完了</a>
  </div>
  {% endfor %}
  <a href="{% url 'logout' %}">ログアウト</a>
</div>
{% endblock content %}

templates/project.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>案件リスト</h1>
{% endblock header %}

{% block content %}
<div class="container">
  {% for project in project_list %}
  <div class="alert alert-success" role="alert">
    <p>{{ project.name }} [{{ project.start_date }}-{{ project.end_date }}] {{ project.phase }}</p>
    <a href="{% url 'project_detail' project.pk %}" class="btn btn-primary btn active" role="button" aria-pressed="true">詳細</a>
    <a href="{% url 'project_resource' project.pk %}" class="btn btn-primary btn active" role="button" aria-pressed="true">リソース管理</a>
  </div>
  {% endfor %}
  <a href="{% url 'project_add' %}" class="btn btn-primary btn active" role="button" aria-pressed="true">追加</a>
</div>
{% endblock content %}

templates/project_add.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>案件追加</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <form action="" method="POST">{% csrf_token %}
    <p>
      <label for="id_name">Name:</label>
      <input type="text" name="name" required id="id_name">
    </p>
    <p>
      <label for="id_start_date">Start date:</label>
      <!-- <input type="text" name="start_date" required id="id_start_date"> -->
      <!-- <input type="date" name="start_date" min="2020-01-01" max="2030-12-31" required id="id_start_date"> -->
      <input type="month" name="start_date" min="2020-01" max="2030-12" required id="id_start_date">
    </p>
    <p>
      <label for="id_end_date">End date:</label>
      <!-- <input type="text" name="end_date" required id="id_end_date"> -->
      <input type="month" name="end_date" min="2020-01" max="2030-12" required id="id_start_date">
    </p>
    <p>
      <label for="id_phase">Phase:</label>
      <select name="phase" id="id_phase">
      {% for project_phase in project_phase_list %}
        <option value={{ project_phase.pk }}>{{ project_phase.phase }}</option>
      {% endfor %}
      </select>
    </p>
    <p>マネジメント：
      {% for manager in manager_list  %}
      <label><input type="checkbox" name="manager" value={{ manager.pk }}>{{ manager.username }}</label>
      {% endfor %}
    </p>

    <p>スタッフ：
      {% for staff in staff_list  %}
      <label><input type="checkbox" name="staff" value={{ staff.pk }}>{{ staff.username }}</label>
      {% endfor %}
    </p>
    <!-- {{ form.as_p }} -->
    <input type="submit" value="追加">
  </form>
</div>
{% endblock content %}

templates/project_detail.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>案件詳細</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <form action="" method="POST">{% csrf_token %}
    <p>
      <label for="id_name">Name:</label>
      <input type="text" name="name" required id="id_name" value="{{ project.name }}">
    </p>
    <p>
      <label for="id_start_date">Start date:</label>
      <!-- <input type="text" name="start_date" required id="id_start_date" value="{{ project.start_date }}"> -->
      <input type="month" name="start_date" min="2020-01" max="2030-12" required id="id_start_date" value="{{ project.start_date }}">
    </p>
    <p>
      <label for="id_end_date">End date:</label>
      <!-- <input type="text" name="end_date" required id="id_end_date" value="{{ project.end_date }}"> -->
      <input type="month" name="end_date" min="2020-01" max="2030-12" required id="id_start_date" value="{{ project.end_date }}">
    </p>
    <p>
      <label for="id_phase">Phase:</label>
      <select name="phase" id="id_phase">
        {% for project_phase in project_phase_list %}
        {% if project_phase.pk == project.phase_id  %}
        <option selected value={{ project_phase.pk }}>{{ project_phase.phase }}</option>
        {% else %}
        <option value={{ project_phase.pk }}>{{ project_phase.phase }}</option>
        {% endif %}
        {% endfor %}
      </select>
    </p>
    <p>マネジメント：
      {% for manager in manager_list  %}
      {% if manager in project_manager_list %}
      <label><input checked type="checkbox" name="manager" value={{ manager.pk }}>{{ manager.username }}</label>
      {% else %}
      <label><input type="checkbox" name="manager" value={{ manager.pk }}>{{ manager.username }}</label>
      {% endif %}
      {% endfor %}
    </p>

    <p>スタッフ：
      {% for staff in staff_list  %}
      {% if staff in project_staff_list %}
      <label><input checked type="checkbox" name="staff" value={{ staff.pk }}>{{ staff.username }}</label>
      {% else %}
      <label><input type="checkbox" name="staff" value={{ staff.pk }}>{{ staff.username }}</label>
      {% endif %}
      {% endfor %}
    </p>
    <!-- {{ form.as_p }} -->
    <input type="submit" value="保存">
  </form>
</div>
{% endblock content %}

templates/project_resource.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>案件リソース管理</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <div class="alert alert-success" role="alert">
    <p>{{ project.name }} [{{ project.start_date }} - {{ project.end_date }}] {{ project.phase }}</p>
  </div>
  <form action="" method="POST">{% csrf_token %}
    <!-- TODO: 後でcssで真ん中寄せ -->
    <table border="1" align="center">
      <tr align="center">
        <th width="100" rowspan="2">月</th>
        {% for project_month in project_month_list %}
        <th colspan="2">{{ project_month }}</th>
        {% endfor %}
      </tr>
      <tr align="center">
        {% for project_month in project_month_list %}
        <th width="50">予定</th>
        <th width="50">実績</th>
        {% endfor %}
      </tr>
      {% for project_member in project_member_list %}
      <tr align="center">
        <th>{{ project_member.user.username }}</th>
        {% for monthly_working_time in monthly_working_time_list %}
        {% if monthly_working_time.project_member.user == project_member.user %}
        <td>
          <input
            style="width:50px;"
            type="number"
            value={{ monthly_working_time.planed_working_time }}
            name="{{ monthly_working_time.project_member_id }}_{{ monthly_working_time.target_month }}_planed"
            class="monthly_working_time"
          >
        </td>
        <td>
          <input
            style="width:50px;"
            type="number"
            value={{ monthly_working_time.actual_working_time }}
            name="{{ monthly_working_time.project_member_id }}_{{ monthly_working_time.target_month }}_actual"
            class="monthly_working_time"
          >
        </td>
        {% endif %}
        {% endfor %}
      </tr>
      {% endfor %}
    </table>
    <input type="text" name="updated_list" id="updated_list" hidden>
    <input type="submit" value="更新">
  </form>
  <p>
    <canvas id="myChart" width="600" height="400">お使いのブラウザはcanvasに対応していません。</canvas>
  </p>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'project_resource.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.1/Chart.js"></script>
<script src="https://unpkg.com/chartjs-plugin-colorschemes"></script>
<script>
  {% autoescape off %}
  var result = {{ result }}
  var project_month_list = {{ project_month_list }}
  // var project_member_list = {{ project_member_list }}
  var j_project_member_list = {{ j_project_member_list }}
  {% endautoescape %}
  // console.log(result)
  // console.log(project_member_list)
  // console.log(j_project_member_list)
  // product = JSON.parse('{{ order_items | safe }}')

  // const data = JSON.parse('{{ j_project_member_list|safe }}');
  // console.log(data);  // [1, 2, 3]

  backgroundColors = ['#3A81F1', '#2DA94F', '#FDBD00', '#EA4335', '#5F6368']

  var datasets = []
  for (let index = 0; index < j_project_member_list.length; index++) {
    const project_member = j_project_member_list[index];
    console.log(project_member);
    diff = []
    result.forEach(r => {
      if (project_member == r[1]) {
        diff.push(r[2])
      }
    })
    data = {
      label: project_member,
      borderWidth: 1,
      backgroundColor: backgroundColors[index],
      data: diff
    }
    datasets.push(data)


  }
  // for (let index = 0; index < project_month_list.length; index++) {
  //   const project_month = project_month_list[index];
  //   diff = []
  //   result.forEach(r => {
  //     console.log(r[0])
  //     console.log(project_month);
  //     console.log(r[0] == project_month)
  //     if(r[0] == project_month){
  //       diff.push(r[2])
  //       console.log(r[1]);
  //       // console.log(diff);
  //     }
  //   });
  //   var data = {
  //     label: project_month,
  //     borderWidth: 1,
  //     backgroundColor: backgroundColors[index],
  //     data: diff
  //   }
  //   datasets.push(data)

  // }
  console.log('datasets');
  console.log(datasets)

  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: project_month_list,
      datasets: datasets
    },
    options: {
      title: {
        display: true,
        text: 'リソース状況', //グラフの見出し
        padding: 3
      },
      scales: {
        xAxes: [{
          stacked: true, //積み上げ棒グラフにする設定
          categoryPercentage: 0.4 //棒グラフの太さ
        }],
        yAxes: [{
          stacked: true //積み上げ棒グラフにする設定
        }]
      },
      legend: {
        labels: {
          boxWidth: 30,
          padding: 20 //凡例の各要素間の距離
        },
        display: true
      },
      tooltips: {
        mode: 'label' //マウスオーバー時に表示されるtooltip
      },
      plugins: {
        colorschemes: {
          scheme: 'brewer.Paired12'
        }
      }
    }
  });
</script>
{% endblock script %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<form class="form-signin" method="POST" action=''>{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">サインアップする</h1>
  {% if error %}
  {{ error }}
  {% endif %}
  <label for="inputEmail" class="sr-only">メールアドレス</label>
  <input type="text" id="inputEmail" class="form-control" name="username" placeholder="ユーザーネーム" required autofocus>
  <label for="inputPassword" class="sr-only">パスワード</label>
  <input type="password" id="inputPassword" class="form-control" name="password" placeholder="パスワード" required>
  <button class="btn btn-lg btn-primary btn-block" type="submit">サインアップ</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
</form>
{% endblock content %}

templates/working_time.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<h1>稼働実績</h1>
{% endblock header %}

{% block content %}
<div class="container">
  <div class="alert alert-success" role="alert">
  </div>
</div>
{% endblock content %}